### ISSUE TITLE
Fix it or Trash it

### ISSUE THREAD

**Issue by JasonAurich** [mattly/atom-colors-pencil-dark#1]
This thing does NOT work well with deprecation-cop. It throws an error every time I click.

**Comment by mattly** [comment]
Do you have a specific issue, or can at least pinpoint what's wrong? I rarely use Atom anymore, but the theme still holds up. I'm not about to delete something I published because some asshole comes along and says I should.

**Comment by jerrett** [comment]
If there's a specific issue with the theme and "deprecation-cop", it seems it might not be too hard to fix and issue a PR? Or provide a bit more details!
